[tool.poetry]
name = "astrea"
version = "0.0.0"
description = ""
authors = ["Artem Shepelin <4.shepelin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = [
    "setuptools>=42",
    "wheel>=0.38.4",
    "ninja>=1.11.1",
    "cmake>=3.12",
    "conan>=2.0.4",
]
build-backend = "setuptools.build_meta"
