[tool.poetry]
name = "lss"
version = "0.1.0"
description = ""
authors = ["deverte <deverte@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.0.0"
numpy = "^1.24.2"
matplotlib = "^3.7.1"
pandas = "^1.5.3"
sympy = "^1.11.1"


[build-system]
requires = [
    "setuptools",
    "conan",
    "cmake",
]
build-backend = "setuptools.build_meta"
