[tool.poetry]
name = "astrea"
version = "0.2.3" # Makefile
description = ""
authors = ["Artem Shepelin <4.shepelin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = [
    "setuptools>=33",
    "wheel>=0.30",
    "ninja>=1.7",
    "cmake>=3",
    "conan>=2",
]
build-backend = "setuptools.build_meta"
