#pragma once


#include "./calculation/lte.h"
#include "./calculation/nlte.h"
#include "./data/elements/element.h"
#include "./data/elements/h1.h"
#include "./data/elements/h2.h"
#include "./data/elements/he1.h"
#include "./data/elements/he2.h"
#include "./data/elements/o1_mashonkina.h"
#include "./data/elements/o2_mashonkina.h"
#include "./data/spectra/black_body_planck.h"
#include "./data/spectra/kelt_9_fossati.h"
#include "./data/spectra/spectrum.h"
#include "./data/spectra/sun_gueymard.h"
#include "./transitions/cbb_mashonkina_o1.h"
#include "./transitions/cbb_regemorter.h"
#include "./transitions/ci_mashonkina_o1_seaton.h"
#include "./transitions/pi_mashonkina_o1.h"
#include "./transitions/rbb_mashonkina_doppler_o1.h"
#include "./transitions/rbb_mashonkina_voigt_o1.h"
#include "./transitions/rbb_tasitsiomi.h"
#include "./transitions/rr_mashonkina_o1.h"
#include "./transitions/se_nist_o1.h"
#include "./transitions/tbr_mashonkina_o1_seaton.h"