name: "release"

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [macos-latest]
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        shell: bash
        run: |
          python3 -m pip install --upgrade \
            cibuildwheel==3.1.3 \
            pip \
            twine

      - name: Build wheel
        shell: bash
        env:
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y \
              ninja-build

            git clone --branch v0.8.0 https://github.com/deverte/astrea # managed by justfile
            mkdir -p astrea/build
            cd astrea/build && \
              cmake .. -G Ninja && \
              ninja install && \
              cd ..

            git clone --branch 3.4.0 https://gitlab.com/libeigen/eigen
            mkdir -p eigen/build
            cd eigen/build && \
              cmake .. -G Ninja && \
              ninja install && \
              cd ..
          CIBW_BEFORE_ALL_MACOS: |
            brew install eigen

            git clone --branch v0.8.0 https://github.com/deverte/astrea # managed by justfile
            mkdir astrea/build
            cd astrea/build && \
              cmake .. -G Ninja && \
              sudo ninja install && \
              cd ..
          CIBW_BEFORE_ALL_WINDOWS: |
            choco install -y `
              cmake `
              eigen --version 3.4.0 `
              ninja

            git clone --branch v0.8.0 https://github.com/deverte/astrea # managed by justfile
            mkdir astrea/build
            cd astrea/build && `
              cmake .. -G Ninja && `
              ninja install && `
              cd ..
          CIBW_ENVIRONMENT_LINUX: |
            Eigen3_INCLUDE_DIRS="/usr/local/include/eigen3"
          CIBW_ENVIRONMENT_MACOS: |
            astrea_INCLUDE_DIRS="/usr/local/include/astrea"
          CIBW_ENVIRONMENT_WINDOWS: |
            EIGEN_PATH="C:/Program Files/eigen3"
          CIBW_BEFORE_BUILD: |
            pip3 install pybind11

            PYBIND11_PATH=$(python3 -c "import pybind11; print(pybind11.get_cmake_dir())")
            PYTHON_PATH=$(python3 -c "import sys; print(sys.prefix.replace('\\\\', '/'))")

            mkdir -p build
            cd build && \
              cmake .. \
                -G Ninja \
                -DCMAKE_PREFIX_PATH="$PYBIND11_PATH" && \
              cmake --build .
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      # - name: Publish to PyPI
      #   if: success()
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     python -m twine upload --skip-existing wheelhouse/*.whl
