name: "release"

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v3

      - uses: actions/setup-cmake@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade \
            build \
            ninja \
            pip \
            pybind11 \
            twine \
            wheel

      - name: Install Astrea
        run:
          git clone --branch v0.8.0 https://github.com/deverte/astrea # managed by justfile
          mkdir astrea/build
          cd astrea/build; \
            cmake -G Ninja ..; \
            ninja; \
            ninja install

      - name: Install Eigen
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y libeigen3-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install eigen
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install eigen --version 3.4.0
          fi

      - name: Build wheel
        run: |
          just configure
          just build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.whl

      - name: Publish to PyPI
        if: success()
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --skip-existing dist/*
