name: "release-linux"

on:
  push:
    tags: ["v*"]

jobs:
  release-linux:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.14"
          - "3.13"
          - "3.12"
        manylinux:
          - image: "manylinux_2_34_x86_64"
            docker: "linux/amd64"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        shell: bash
        run: |
          python3 -m pip install --upgrade \
            pip \
            twine \
            \
            auditwheel \
            build \
            ninja \
            pybind11 \
            setuptools

      - name: Install Eigen
        shell: bash
        run: |
          git clone --branch 3.4.0 https://gitlab.com/libeigen/eigen && \
          mkdir eigen/build && \
          cd eigen/build && \
            cmake .. -G Ninja && \
            sudo ninja install && \
            cd ..

      - name: Install Astrea
        shell: bash
        run: |
          git clone --branch v0.8.1 https://github.com/deverte/astrea # managed by justfile
          mkdir -p astrea/build && \
          cd astrea/build && \
            cmake .. -G Ninja && \
            sudo ninja install && \
            cd ..

      - name: Build wheel (Linux)
        shell: bash
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          export Eigen3_INCLUDE_DIRS="/usr/local/include/eigen3"
          export PYBIND11_PATH=$(python3 -c "import pybind11; print(pybind11.get_cmake_dir())")

          mkdir -p build && \
          cd build && \
            cmake .. \
              -G Ninja \
              -DCMAKE_PREFIX_PATH="$PYBIND11_PATH" \
              -DCMAKE_BUILD_TYPE=Release && \
            cmake --build . && \
            cd ..

          mkdir -p /dist
          python3 -m build --no-isolation --wheel --outdir /dist
          python3 -m auditwheel repair /dist/*.whl -w ./wheelhouse

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.manylinux.image }}
          path: ./wheelhouse/*.whl

      - name: Publish to PyPI
        if: success()
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --skip-existing wheelhouse/*.whl
